# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mariusz Kotas blog
email: m@mkotas.cz
description: > # this means to ignore newlines until "baseurl:"
  Software Craftsman notes
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mkotas.cz" # the base hostname & protocol for your site
twitter_username: marfusios
github_username:  marfusios

# Build settings
markdown: kramdown
